FROM ubuntu:16.04
MAINTAINER Denilson Ferreira <denilsonpfus@gmail.com>
ENV REFRESHED_AT 2017-06-23 02:37

ADD  https://github.com/denilsonpfus/new_site/blob/master/Index.html ./var/www/html/
#COPY $PWD/new_site/ ./var/www/html/

VOLUME /data
VOLUME /var/www/html
WORKDIR /data

